### ISSUE TITLE
出现滚动条以后，提示框就定位不准了

### ISSUE THREAD

**Issue by blinkcat** [zhujun24/At#1]
提示框的top要减去textarea的scrollTop

**Comment by zhujun24** [comment]
我还没有发现哎，麻烦说明一下具体情况，最好截个图 @blinkcat

**Comment by zhujun24** [comment]
@blinkcat 修复了这个Bug，已经Push了，今晚部署到SAE上去，你可以clone到本地看看，感谢您的反馈
