### ISSUE TITLE
怎么给@的文字添加样式呢？

### ISSUE THREAD

**Issue by BrookeShan** [zhujun24/At#2]
想要给@及@的名字添加字体样式，但是多次尝试后无解。不知楼主是否有设么想法可提供参考？

**Comment by zhujun24** [comment]
那得使用 `contenteditable` 属性了，参见[http://www.w3school.com.cn/html5/att_global_contenteditable.asp](http://www.w3school.com.cn/html5/att_global_contenteditable.asp)
